joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

arm_joint_controller:
  ros__parameters:
    type: effort_controllers/JointPositionController
    joint: arm_joint
    pid:
      p: 1.0
      i: 0.0
      d: 0.1
